//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by MSBuild generator.
//     Source: OptionalFields.cs
// </auto-generated>
//------------------------------------------------------------------------------

using GodSharp.Extensions.Opc.Ua.Types;
using GodSharp.Extensions.Opc.Ua.Types.Encodings;
using static GodSharp.Extensions.Opc.Ua.Types.Encodings.EncodingFactory;
using Opc.Ua;
using System.Collections.Generic;
using GodSharp.Extensions.Opc.Ua.Utilities;
using System.Linq.Expressions;
using System;

namespace OpcUaTest
{
	public partial class OptionalFields : ComplexObject 
	{
		public uint EncodingMask;

		public override void Encode(IEncoder encoder)
		{
			base.Encode(encoder);
			encoder.WriteUInt32("EncodingMask",EncodingMask);
			encoder.Write(MandatoryInt32, nameof(MandatoryInt32));
			if ((0x01 & EncodingMask) != 0)
			{
				encoder.Write(OptionalInt32, nameof(OptionalInt32));
			}
			encoder.Write(MandatoryStringArray, nameof(MandatoryStringArray));
			if ((0x02 & EncodingMask) != 0)
			{
				encoder.Write(OptionalStringArray, nameof(OptionalStringArray));
			}
		}

		public override void Decode(IDecoder decoder)
		{
			base.Decode(decoder);
			EncodingMask = decoder.ReadUInt32("EncodingMask");
			decoder.Read(ref MandatoryInt32, nameof(MandatoryInt32));
			if ((0x01 & EncodingMask) != 0)
			{
				decoder.Read(ref OptionalInt32, nameof(OptionalInt32));
			}
			decoder.Read(ref MandatoryStringArray, nameof(MandatoryStringArray));
			if ((0x02 & EncodingMask) != 0)
			{
				decoder.Read(ref OptionalStringArray, nameof(OptionalStringArray));
			}
		}

		public OptionalFields ResetMask()
		{
			EncodingMask = 0;
			return this;
		}

		public OptionalFields WithOptionalField<TMember>(Expression<Func<OptionalFields, TMember>> predicate) => WithOptionalField(ExpressionHelper.GetMemberName(predicate.Body));

		public OptionalFields WithOptionalField(string field)
		{
			switch (field)
			{
				case "OptionalInt32":
					EncodingMask |= 0x01;
					break;
				case "OptionalStringArray":
					EncodingMask |= 0x02;
					break;
			}
			return this;
		}
	}
}
