//------------------------------------------------------------------------------
// <auto-generated>
//     Generated by MSBuild generator.
//     Source: Vector.cs
// </auto-generated>
//------------------------------------------------------------------------------

using GodSharp.Extensions.Opc.Ua.Types;
using Opc.Ua;
using GodSharp.Extensions.Opc.Ua.Types.Encodings;
using static GodSharp.Extensions.Opc.Ua.Types.Encodings.EncodingFactory;

namespace OpcUaTest
{
	public partial class UaOrgVector : ComplexObject
	{
		public override void Encode(IEncoder encoder)
		{
			base.Encode(encoder);
			Encoding.Write(encoder, X, nameof(X));
			Encoding.Write(encoder, Y, nameof(Y));
			Encoding.Write(encoder, Z, nameof(Z));
		}

		public override void Decode(IDecoder decoder)
		{
			base.Decode(decoder);
			Encoding.Read(decoder, ref X, nameof(X));
			Encoding.Read(decoder, ref Y, nameof(Y));
			Encoding.Read(decoder, ref Z, nameof(Z));
		}
	}

	public partial class ProsysVector : ComplexObject
	{
		public override void Encode(IEncoder encoder)
		{
			base.Encode(encoder);
			Encoding.Write(encoder, X, nameof(X));
			Encoding.Write(encoder, Y, nameof(Y));
			Encoding.Write(encoder, Z, nameof(Z));
		}

		public override void Decode(IDecoder decoder)
		{
			base.Decode(decoder);
			Encoding.Read(decoder, ref X, nameof(X));
			Encoding.Read(decoder, ref Y, nameof(Y));
			Encoding.Read(decoder, ref Z, nameof(Z));
		}
	}

	public partial class UaAnsiVector : ComplexObject
	{
		public override void Encode(IEncoder encoder)
		{
			base.Encode(encoder);
			encoder.Write(X, nameof(X));
			encoder.Write(Y, nameof(Y));
			encoder.Write(Z, nameof(Z));
		}

		public override void Decode(IDecoder decoder)
		{
			base.Decode(decoder);
			decoder.Read(ref X, nameof(X));
			decoder.Read(ref Y, nameof(Y));
			decoder.Read(ref Z, nameof(Z));
		}
	}
}
